logging:
  level:
    root: ${LOGGING:debug}

server:
  port: ${PORT:8080}

spring:
  application:
    name: trdosl

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5488}/${DB_NAME:trdosl-db}
    username: ${DB_USER:trdosl}
    password: ${DB_PASSWORD:trdosl}
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
