logging:
  level:
    root: debug

spring:
  application:
    name: trdosl

  datasource:
    url: jdbc:postgresql://localhost:5488/trdosl-db
    username: trdosl
    password: trdosl
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration